### ISSUE TITLE
Reduce GRIP Latency

### ISSUE THREAD

**Issue by KevinMackenzie** [Team-1922/TinMan2016#30]
Right now the latency from the camera view to a network steam across LAN is about 1.5 seconds.  This is too much; GRIP will not be as bad, because it only has to stream to localhost, however it still adds latency to encode the video and there is still processing grip needs to do.

Potential Methods:
-Reduce Resolution (ouch, to like 120p; not ideal)
-Get GRIP to run on USB camera instead of encoding to network stream (this might be impossible)

**Comment by KevinMackenzie** [comment]
the latency is only about 1 second now on the local network, and not streaming the whole video.

**Comment by KevinMackenzie** [comment]
it might make sense to try and roll our own openCV app that still outputs to network tables, but doesn't go through the fuss of a USB device converted to a network stream and causing pointless latency

**Comment by KevinMackenzie** [comment]
we might be best of using OpenCV in python and use the network tables python port found here:
https://github.com/robotpy/pynetworktables/tree/master/networktables

Mostly because my experience of python has much more rapid development and testing
OpenCV here for python (also includes loading from camera):
http://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html

**Comment by KevinMackenzie** [comment]
would it make more sense to continue doing threshold testing, or something more advanced like cascade testing?  I'd say do threshold testing to start, because we are already have those values validated somewhat

**Comment by AndrewRPorter** [comment]
I think it still makes sense to do threshold testing.

**Comment by KevinMackenzie** [comment]
no more GRIP, now python with openCV, comparable results achieved, but with lower latencies and more flexible.
